spring.application.name=Infotech
server.port = 8082
spring.datasource.url =jdbc:postgresql://localhost:5432/Ajinkya
spring.datasource.username=postgres
spring.datasource.password = Kalpesh@2005
spring.jpa.hibernate.ddl-auto = update
spring.security.user.name = kalpesh
spring.security.user.password = 1234
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shirsathkalpesh2005@gmail.com
spring.mail.password=euzb kmch zrda aulw

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# Max file size
spring.servlet.multipart.max-file-size=10MB

# Max request size
spring.servlet.multipart.max-request-size=10MB

cloudinary.cloud-name=da124v4jx
cloudinary.api-key=335655349942471
cloudinary.api-secret=lvUxsd8PPz2qWoFifPTqYIhip-A
